swagger: "2.0"
info:
  description: "This is my peeopoe university project."
  version: "1.0.0"
  title: "web scraper"
  termsOfService: "jmatejik.eu"
  contact:
    email: "jakub.matejik@centrum.cz"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8083"
basePath: "/"
tags:
- name: "webpage"
  description: "Webpages"
- name: "node"
  description: "Nodes for visualizing graph"
- name: "execution"
  description: "Executions"
schemes:
- "https"
- "http"
paths:
  /executions:
    get:
      tags:
      - "execution"
      summary: "Returns webpages"
      description: "Returns a map of status codes to quantities"
      operationId: "getExecutions"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
            additionalProperties:
              type: "integer"
              format: "int32"
  /nodes:
    get:
      tags:
      - "node"
      summary: "Returns nodes fro graph"
      description: "Returns a map of nodes"
      operationId: "getNodes"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/NodesObject"
  /webpages/:
    post:
      tags:
      - "webpage"
      summary: "Add a new webpage record"
      description: ""
      operationId: "addWebpage"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Webpage object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/WebpageIn"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/WebpageOut"
        "400":
          description: "Invalid ID supplied"
      security: []
    get:
      tags:
      - "webpage"
      summary: "get webpages"
      description: "Returns a webpages"
      operationId: "getWebpages"
      produces:
      - "application/xml"
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/WebpageOut"
  /webpages/{id}:
    put:
      tags:
      - "webpage"
      summary: "Update an existing webpages"
      description: ""
      operationId: "updateWebpage"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "name that need to be updated"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "webpage object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/WebpageIn"
      responses:
        "400":
          description: "Invalid ID supplied"
    get:
      tags:
      - "webpage"
      summary: "Find webpage by ID"
      description: "Returns a single webpage"
      operationId: "getWebpageById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "name that need to be updated"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/WebpageOut"
        "400":
          description: "Invalid ID supplied"
    delete:
      tags:
      - "webpage"
      summary: "Deletes a "
      description: ""
      operationId: "deletewebpage"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of webpage to delete"
        required: true
        type: "string"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "webpage not found"
definitions:
  WebpageIn:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      url:
        type: "string"
      regexp:
        type: "string"
      active:
        type: "string"
      label:
        type: "string"
      periodicity:
        type: "string"
      tags:
        type: "string"
    xml:
      name: "Webpage"
  Node:
    type: object
    properties:
      title:
        type: "string"
      url:
        type: "string"
      crawlTime:
        type: "string"
      owner:
        type: "string"
      links:
        type: array
        items:
          type: "string"
  Execution:
    type: object
    properties:
      status:
        type: "string"
      start:
        type: "string"
      end:
        type: "string"
      sitesCrawled:
        type: array
        items:
          type: "string"
  WebpageOut:
    type: object
    properties:
      id:
        type: "string"
      url:
        type: "string"
      regexp:
        type: "string"
      tags:
        type: "array"
        items:
          type: "string"
      active:
        type: "string"
      periodicity:
        type: "string"
      executions:
        type: array
        items:
          $ref: "#/definitions/Execution"
      nodes:
        type: array
        items:
          $ref: "#/definitions/Node"
      label:
        type: "string"
      regexps:
        type: array
        items:
          type: "string"
  NodesObject:
    type: object
    properties:
      nodes:
        type: array
        items:
          $ref: "#/definitions/GraphNode"
      links:
        type: array
        items:
          $ref: "#/definitions/Link"
  GraphNode:
    type: object
    properties:
      id:
        type: "string"
      webpageId:
        type: "string"
      webpageTags:
        type: "string"
      webpageActive:
        type: "string"
      label:
        type: "string"
      color:
        type: "string"
      links:
        type: array
        items:
          type: "string"
      isCrawled:
        type: "boolean"
      crawledBy:
        type: array
        items:
          type: "string"
      regexps:
        type: array
        items:
          type: "string"
  Link:
    type: object
    properties:
      source:
        type: "integer"
      target:
        type: "integer"